version: "3.6"

services:
  alpine-dev:
    container_name: alpine-dev
    build: .
    restart: unless-stopped
    environment:
      # This exposes the environment variable into the container when it runs
      - DOCKER_SSH_PORT
    volumes:
      - private:/data/private   # volume only mounted with this container
      - shared:/data/shared     # volume shared with all other containers
      - /sys/class/gpio/gpio34/value:/hardware/efr32reset
      - /sys/devices/soc0/pwm_leds/leds:/hardware/leds
      - /var/lib/dhcpcd:/var/lib/dhcpcd
      - /run/dhcpcd_status:/run/dhcpcd_status
      - /usr/bin/wiser:/usr/bin/wiser # scripts to get/set factory settings
      - /var/run:/var/run # FIFO for factory setting scripts
      - /tmp:/tmp
      
    ports:
      # WARNING: This is exposing these ports to the outside world and should not be done in productions 
      # without serious thinking!

      # This is the ssh port used by the alpine development container so you can get a shell inside the container
      - ${DOCKER_SSH_PORT-2222}:${DOCKER_SSH_PORT-2222}
      # This is the gdb server port used by the alpine development container so you can connect to it from your dev host
      - ${GBDSERVER_PORT-2159}:${GBDSERVER_PORT-2159}
      # Only expose this port if you are bypassing NGINX
      # - ${HTTP_PORT-8080}:8080
    devices:
      # The zigbee UART device should be found at /dev/ttymxc2 on standard hub
      - /dev/ttymxc2:/hardware/efr32uart
      # The application CLI UART device should be found at /dev/ttymxc1 on standard hub
      - /dev/ttymxc1:/hardware/cliuart
      # Setup button events are on /dev/input/
      - /dev/input:/hardware/setupbutton
    networks:
      # Use "wiser-central" to refer the top level network named below
      - wiser-central

networks:
  # wiser-central is a label but "wiser-net" is the named docker bridge network that all apps will connect to
  # This allows them to be found via their service name
  wiser-central:
    external:
      name: wiser-net

volumes:
  private: # alpine-dev's private data
    name: alpine-dev
  shared: # shared volume
    name: shared
