SET(CMAKE_SYSTEM_NAME Linux)

# Pointers to the C/C++ compilers
SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(TOOLCHAIN_ROOT_CMAKE ${CMAKE_SOURCE_DIR}/toolchains/armv7l-linux-musleabihf-cross)
SET(CMAKE_C_COMPILER "${TOOLCHAIN_ROOT_CMAKE}/bin/armv7l-linux-musleabihf-gcc")
SET(CMAKE_CXX_COMPILER "${TOOLCHAIN_ROOT_CMAKE}/bin/armv7l-linux-musleabihf-g++")

set(CMAKE_SYSROOT ${CMAKE_SOURCE_DIR}/toolchains/armv7l-linux-musleabihf-cross)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)